[workspace]
members = [
    "crates/common",
    "crates/daemon",
    "crates/cli",
    "crates/tray",
    "crates/backend-usbguard",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = true
