[package]
name = "guardianusb-backend-mock"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["MK2112"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
guardianusb-common = { path = "../common" }
async-trait = "0.1"
